version: '3.8'

services:
  # --- API GATEWAY ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./public.key:/app/keys/public.key:ro
    depends_on:
      - user-service
      - transaction-service
      - notification-service
    networks:
      - family-net

  # --- USER SERVICE (REST) ---
  user-service:
    build: ./user-service
    volumes:
      - ./private.key:/app/keys/private.key:ro
    expose:
      - "3001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=user_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - family-net

  # --- TRANSACTION SERVICE (GraphQL) ---
  transaction-service:
    build: ./transaction-service
    expose:
      - "3002"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=transaction_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - notification-service
    networks:
      - family-net

  # --- NOTIFICATION SERVICE (REST) ---
  notification-service:
    build: ./notification-service
    expose:
      - "3003"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=notification_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - family-net

  # --- FRONTEND ---
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    networks:
      - family-net

networks:
  family-net:
    driver: bridge