version: '3.8'

services:
  # --- API GATEWAY ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./public.key:/app/keys/public.key:ro # Hanya butuh Public Key
    depends_on:
      - user-service
      - transaction-service
    networks:
      - family-net

  # --- USER SERVICE (REST) ---
  user-service:
    build: ./user-service
    volumes:
      - ./private.key:/app/keys/private.key:ro # Butuh Private Key untuk Sign Token
    expose:
      - "3001"
    networks:
      - family-net

  # --- TRANSACTION SERVICE (GraphQL) ---
  transaction-service:
    build: ./transaction-service
    expose:
      - "3002"
    networks:
      - family-net

  # --- FRONTEND (Dummy) ---
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - family-net

networks:
  family-net:
    driver: bridge