version: '3.8'

services:
  # --- API GATEWAY ---
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./public.key:/app/keys/public.key:ro
    depends_on:
      - user-service
      - transaction-service
    networks:
      - family-net

  # --- USER SERVICE (REST) ---
  user-service:
    build: ./user-service
    volumes:
      - ./private.key:/app/keys/private.key:ro
    expose:
      - "3001"
    networks:
      - family-net

  # --- TRANSACTION SERVICE (GraphQL) ---
  transaction-service:
    build: ./transaction-service
    expose:
      - "3002"
    networks:
      - family-net

  # --- FRONTEND ---
  # Pastikan Dockerfile frontend sudah Anda buat sesuai panduan sebelumnya
  frontend:
    build: ./frontend
    ports:
      - "5173:80" # Mapping port host 5173 ke container 80 (nginx)
    networks:
      - family-net

networks:
  family-net:
    driver: bridge